Migrate to Vue 3:
ABI-Software/plotvuer pull request #35
Opened 2024-01-25 02:45 UTC by Tehsurfer

Filtering options were removed as they are not used on sparc.science anymore

2024-02-04 23:40 UTC, alan-wu requested changes
All the map svg icons are not displaying as they are commented out. The props for el-popover have been changed in element-plus so they need to be updated. Please update your pull request.

2024-02-05 00:14 UTC, alan-wu reviewed
With vite - export should be stated in the package.json file now - similar to the following:

```
  "type": "module",
  "main": "./dist/scaffoldvuer.umd.cjs",
  "module": "./dist/scaffoldvuer.js",
  "exports": {
    ".": {
      "import": "./dist/scaffoldvuer.js",
      "require": "./dist/scaffoldvuer.umd.cjs"
    },
    "./dist/style.css": "./dist/style.css",
    "./src/*": "./src/*"
  },
```

2024-02-07 23:27 UTC, Tehsurfer commented on package.json
>      "element-ui": "^2.13.0",
@alan-wu Remove element-ui right?

2024-02-07 23:59 UTC, alan-wu commented on package.json
>      "element-ui": "^2.13.0",
Yes, element-ui. I somehow targeted the wrong line.

2024-02-08 00:00 UTC, alan-wu commented on package.json
>      "element-ui": "^2.13.0",
I did not target the wrong line, it is confusing with the green + colour.

2024-02-14 23:07 UTC, alan-wu approved these changes

2024-02-14 23:08 UTC, merged